name: thicken
description: A widget that creates a thick visual effect by stacking multiple layers of a given child widget with slight translations based on the thickness value.
version: 1.1.2
homepage: https://inidia.app
repository: https://github.com/Nialixus/thicken.git
issue_tracker: https://github.com/Nialixus/thicken/issues
funding:
  - https://ko-fi.com/nialixus
screenshots:
  - description: "Thicken Logo"
    path: logo.png
topics:
  - utility
  - animation

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0